#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
cd "$(dirname $0)"
export PYTHONPATH=$PWD/lib
python lib/exec.py
