apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildkitd
  name: buildkitd
spec:
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
      annotations:
        container.apparmor.security.beta.kubernetes.io/buildkitd: unconfined
        container.seccomp.security.alpha.kubernetes.io/buildkitd: unconfined
    spec:
      containers:
# moby/buildkit:vX.Y.Z-rootless is executed as an unprivileged user (UID=1000).
# If you are using Debian (not Ubuntu) or Arch Linux kernel on each of kubelet nodes,
# `sudo sh -c "echo 1 > /proc/sys/kernel/unprivileged_userns_clone"` is required.
#
# On RHEL/CentOS 7, `sudo sh -c "echo 28633 > /proc/sys/user/max_user_namespaces"` is required.
#
# Note that rootless mode does not support OverlayFS snapshotter unless using Ubuntu kernel.
# However, reflink-based Copy-on-Write can be enabled by mounting XFS volume on /home/user/.local/share/buildkit .
# The XFS volume needs to be formatted with `mkfs.xfs -m reflink=1`.
#
# Also note that rootless mode is known not to work on GCOS kernel: https://github.com/moby/buildkit/issues/879
#
# You can also use rootful moby/buildkit:vX.Y.Z instead.
      - image: moby/buildkit:v0.5.1-rootless@sha256:5a826464a96e11d1c1ee97f35460f8421c6bdafd1d8f20bc11b9d698a179ab0b
        args:
        - --addr
        - unix:///run/user/1000/buildkit/buildkitd.sock
        - --addr
        - tcp://0.0.0.0:1234
# Disable PID namespace isolation across the BuildKit daemon and "RUN" containers.
# To enable PID namespace isolation, you need to remove --oci-worker-no-process-sandbox and
# set securityContext.procMount to "Unmasked" (or set securityContext.privileged to true).
        - --oci-worker-no-process-sandbox
        name: buildkitd
        ports:
        - containerPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: buildkitd
  name: buildkitd
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 1234
    protocol: TCP
  selector:
    app: buildkitd 
